client_config_backend: 'settings'
client_config:
   client_id: "{enter client_id from client_secrets.json file here}"
   client_secret: "{enter client_secret from client_secrets.json file here}"
save_credentials: True
save_credentials_backend: 'file'
save_credentials_file: 'creds.json'
oauth_scope:
- "https://www.googleapis.com/auth/drive"